#!/bin/bash

curl -X POST $DANTED
curl -X POST $ALIYUN_DDNS
curl -X POST $HIDDEN_SFTP
curl -X POST $STRONGSWAN
curl -X POST $BIND9
curl -X POST $OCSERV
curl -X POST $OPENVPN
curl -X POST $OPENVPN_SOCKS
curl -X POST $TOHOKU_ANIME
curl -X POST $CIDR_MERGE
curl -X POST $FREERADIUS
curl -X POST $LUGFTP
curl -X POST $NGINX
curl -X POST $ZHUMU
#curl -X POST
#curl -X POST
#curl -X POST
#curl -X POST
